### ISSUE TITLE
Incorrect number of orbits obtain from 5node graphlet 

### ISSUE THREAD

**Issue by tanjiajun27** [benedekrozemberczki/OrbitalFeatures#1]
Hi Benedekrozembercki,

I’m currently working on graph to count the number of time each orbits occur on each node. And had come across your respo which is what I need.

However the result isn’t correct, for graphlet-size 5 it return only 0-66 orbits, Which is supposedly to be 0-72.

Regards,
Jiajun

**Comment by benedekrozemberczki** [comment]
It only handles graphlets up to size 4.
